Update IPTV.yml

diff --git a/.github/workflows/IPTV.yml b/.github/workflows/IPTV.yml
--- a/.github/workflows/IPTV.yml
+++ b/.github/workflows/IPTV.yml
@@ -3,7 +3,7 @@ env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 on:
   schedule:
-    - cron: '*/1 * * * *'
+    - cron: '*/3 * * * *'
 
 jobs:
   build:
@@ -27,11 +27,12 @@ jobs:
             exit 0
           fi
           rm -f ipv6.m3u Global.m3u
-          
+          echo "Changes detected, proceeding with commit."
+
       - name: Add and commit the merged file
         run: |
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git config --global user.name "github-actions[bot]"
           git add IPTV.m3u
-          git commit -m 'IPTV UPDATE'
-          git push origin main
+          git commit -m 'IPTV UPDATE' || { echo "Commit failed"; exit 1; }
+          git push origin main || { echo "Push failed"; exit 1; }
